# Generated by Django 3.1.3 on 2024-05-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True)),
                ('precio', models.TextField(blank=True)),
                ('descripcion', models.TextField(blank=True)),
                ('url', models.URLField()),
            ],
        ),
    ]
