# Generated by Django 3.1.3 on 2024-05-14 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link',
            new_name='Fake',
        ),
    ]
